In [ ]:
#| default_exp core

# Core

> Module with the main class `Meoinfo`.

In [ ]:
#|hide
from nbdev.showdoc import *

In [ ]:
#|export
from pandas import DataFrame
from fastcore.utils import *


class Meoinfo:

    def __init__(self,
                train_data: DataFrame,            # training dataset
                test_data: DataFrame,             # test dataset, originated from random test/train split
                oot_data: DataFrame,              # out of time dataset
                baseline_y_true_name: str,        # name of the target variable
                baseline_y_prob_name: str,        # name of the probability column of the baseline model
                features: list,                   # list of features
                bad_rate_limit: float = 0,        # the maximum bad rate limit that credit policy should alllow
                scenario: str = "variables",      # "variables" or "score"
                test: str = "all",                # which test to run within the scenario
                weights_name: str = None,         # name of the columns that contains negated inference weights
                baseline_rating_name: str = None, # baseling rating name
                blend_rating_name: str = None,    # blend rating name
                n_features_to_select: int = 10,   # number of features to select from features list
                algorithm: str = "catboost",      # the algorithm to use
                search_params: dict = None        # grid search params
    ):
        store_attr()

In [ ]:
import pandas as pd
from pathlib import Path

p = Path('..')

df_train = pd.read_csv(p/'datasets/churn_train.csv')
df_test = pd.read_csv(p/'datasets/churn_test.csv')
df_oot = pd.read_csv(p/'datasets/churn_oot.csv')

In [ ]:
experiment = Meoinfo(
    train_data=df_train,
    test_data=df_test,
    oot_data=df_oot,
    baseline_y_true_name='Churn',
    baseline_y_prob_name='y_prob',
    features=df_train.drop('Churn', axis=1).columns.tolist()    
)

In [ ]:
experiment.train_data.head()

  gender  SeniorCitizen Partner  ... MonthlyCharges  TotalCharges Churn
0   Male              1     Yes  ...          73.45          5329    No
1   Male              0      No  ...          20.25         178.5   Yes
2   Male              0      No  ...          90.65        6322.1    No
3   Male              0      No  ...          50.30         92.75    No
4   Male              0      No  ...          54.85         370.4    No

[5 rows x 20 columns]

In [ ]:
experiment.test_data.head()

   gender  SeniorCitizen Partner  ... MonthlyCharges  TotalCharges Churn
0  Female              0      No  ...          89.80        1129.1   Yes
1    Male              0     Yes  ...          90.15       6237.05    No
2    Male              1      No  ...          75.65       1146.65   Yes
3    Male              0      No  ...          19.70         415.9    No
4  Female              1      No  ...          85.45       1505.85   Yes

[5 rows x 20 columns]

In [ ]:
experiment.oot_data.head()

   gender  SeniorCitizen Partner  ... MonthlyCharges  TotalCharges Churn
0    Male              1     Yes  ...          94.25        6081.4    No
1  Female              1     Yes  ...         105.00       7578.05    No
2    Male              0     Yes  ...          20.00         879.8    No
3  Female              1      No  ...          73.25        4054.2    No
4  Female              0     Yes  ...          69.00         506.9   Yes

[5 rows x 20 columns]

In [ ]:
experiment.algorithm

'catboost'